---
- name: become root and setup network routing
  import_tasks: root.yml
  become: true
  tags: wrt_net_all

- name: add netfilter shell helpers for user
  blockinfile:
    path: "{{ ansible_user_dir }}/.profile"
    block: "{{ lookup('template', 'shell-helpers.sh') }}"
    marker: '# {mark} NETFILTER SHELL HERLPERS'
    create: true
  tags:
    - wrt_net_user
    - wrt_net_all

- name: run postponed handlers now
  meta: flush_handlers
  tags: wrt_net_all
...
